version: '3'

services:
  db_dev:
    image: mysql:5.7.21
    #        volumes:
    #          - "./volumes/mysql_dev:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_DATABASE=api_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password

#  postgres:
#    image: postgres:10.2
#    #    volumes:
#    #      - "./volumes/postgres:/var/lib/postgresql/data"
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_USER=dbuser
#      - POSTGRES_PASSWORD=dbpass
#      - POSTGRES_DB=api_db